target-version = "py314"
line-length = 100
indent-width = 4
include = ["chearttest"]
exclude = [".venv", "**/build"]
preview = false
[lint]
preview = false
select = ["ALL"]
ignore = [
    "T201",
    "T203",    #COM812: Adds trailing comma to array expressions, resulting in bad autoformatting
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "G004",
    "G010",
    "ERA001",
    "TRY401",
    "PLE1205",
    "S607",
    "S603",
]
fixable = ["ALL"]
unfixable = []
[lint.extend-per-file-ignores]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG",  # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
[format]
quote-style = "double"
indent-style = "space"
